services:
  - type: web
    name: sugar-and-spice-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn sugarandspice.wsgi"
    buildFilters:
      - '**.py'
      - 'requirements.txt'
      - 'render.yaml'

databases:
  - name: sugar-spice-db
    plan: free