# Generated by Django 5.2.4 on 2025-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homeconfig2/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in dollars', max_digits=6, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FarmBooking',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItems',
        ),
        migrations.RenameModel(
            old_name='item',
            new_name='OrderItems',
        ),
        migrations.DeleteModel(
            name='home',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
