# Generated by Django 5.2.4 on 2025-07-16 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workshop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
            ],
        ),
        migrations.DeleteModel(
            name='homeConfig',
        ),
        migrations.DeleteModel(
            name='HomeImages',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'booking_time']},
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='select_date',
        ),
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='select_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('workshop', 'booking_date', 'booking_time')},
        ),
    ]
