# Generated by Django 5.2.4 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepageimage_delete_homeconfig_delete_homeimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('logo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('instragram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('about_title', models.CharField(blank=True, max_length=100, null=True)),
                ('about_description', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('menu_title', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('order_online_title', models.CharField(blank=True, max_length=100, null=True)),
                ('order_online_description', models.TextField(blank=True, null=True)),
                ('order_online_subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('oredr_online_image', models.ImageField(blank=True, null=True, upload_to='order/')),
                ('contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_site_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_text', models.TextField(blank=True, null=True)),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('contact_map_url', models.URLField(blank=True, null=True)),
                ('workshop_title', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_title', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutConfig',
        ),
        migrations.DeleteModel(
            name='BaseConfig',
        ),
        migrations.DeleteModel(
            name='ContactConfig',
        ),
        migrations.DeleteModel(
            name='HomeLinks',
        ),
        migrations.DeleteModel(
            name='MenuConfig',
        ),
        migrations.DeleteModel(
            name='OrderConfig',
        ),
        migrations.DeleteModel(
            name='ScheduleConfig',
        ),
        migrations.DeleteModel(
            name='WorkConfig',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
